### PR TITLE
Select: add useFullWidthItems to allow dropdown with to expand

### PR DESCRIPTION
**Pull request by hoorayimhelping**
Helps with  https://github.com/ClickHouse/control-plane/issues/10057

- Adds `useFullWidthItems` to `Select` props
  - Tells the dropdown to expand its width to accommodate for long content
  - Has a max width of `64ch`, which is approximately 64 characters
  - Adds `itemCharacterLimit` which is only applied when `useFullWidtthItems` to allow overriding the default max widtth of `64ch`
  - Has a min width of the width of the dropdown selector, so that expanding the dropdown selector will cause the dropdown menu to be the same width as it, even if the content is shorter

#### Reasonable length content
Screenshot 2024-08-12 at 9 59 09 AM
#### Very long content
Screenshot 2024-08-12 at 12 09 20 PM
#### Ludicrously long content (clipped at 64 characters)
Screenshot 2024-08-12 at 12 00 00 PM
#### Minimum width of the dropdown selector
Screenshot 2024-08-12 at 11 50 32 AM
#### `itemCharacterLimit="32ch"`
Screenshot 2024-08-12 at 12 34 52 PM
#### itemCharacterLimit="200ch" (can break things if not careful)
Screenshot 2024-08-12 at 12 35 59 PM

### CODE REVIEW

**Review by ArctypeZach — APPROVED** [review]

**Comment by gjones** [comment]
@hoorayimhelping I don't think we should allow the **Ludicrously long content** example, perhaps we can add a limit? 64 chars? 

Also does this also allow the service select dropdown to be wider or not? As I know we've had plenty of feedback that its too narrow.

**Comment by gjones** [comment]
@hoorayimhelping Maybe a `maxChars` prop?

**Comment by ArctypeZach** [comment]
@gjones this would allow us to make the service selector wider as well

**Comment by hoorayimhelping** [comment]
@gjones I set the `max-width` to `64ch` and replaced the outdated screenshots. What do you think?

**Comment by gjones** [comment]
@hoorayimhelping Yeah I think that's a good default limit, (I still think a prop to override it would provide really useful flexibility though)

**Comment by hoorayimhelping** [comment]
@gjones alright, I'll add that limit as a prop (was hoping I could be lazy, but alas 😉)

**Comment by gjones** [comment]
ha ha, sorry 😄

**Review by gjones — APPROVED** [review]

**Comment by hoorayimhelping** [comment]
I looked into writing unit tests for this logic, but it's not possible (or is very difficult and brittle) to test text truncation using react-testing-library

**Pull request merged**
